name: SocialLinks
version: '1.1.2'
description: 'Easily generate Social Sharing Links'
url: 'https://github.com/aerni/statamic-social'
developer: 'Michael Aerni'
developer_url: https://www.michaelaerni.ch